const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {allowedMedia}=require('./core.cjs');
async function imageBytes(url){if(!allowedMedia(url))throw new Error('不支持该图片域名。');let res;for(let n=0;n<5;n++){res=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000),headers:{Referer:'https://www.douyin.com/'}});if(res.status>=300&&res.status<400){const next=res.headers.get('location');await res.body?.cancel();url=new URL(next,url).href;if(!allowedMedia(url))throw new Error('图片重定向域名不受支持。');continue;}break;}
 if(!res.ok)throw new Error('图片获取失败：'+res.status);const type=(res.headers.get('content-type')||'').split(';')[0];if(!['image/jpeg','image/png','image/webp','image/gif','image/avif'].includes(type)){await res.body?.cancel();throw new Error('图片格式不支持。');}
 if(Number(res.headers.get('content-length'))>20*1024*1024){await res.body?.cancel();throw new Error('图片超过 20 MB。');}const chunks=[];let length=0;for await(const chunk of res.body){length+=chunk.length;if(length>20*1024*1024){throw new Error('图片超过 20 MB。');}chunks.push(chunk);}return {bytes:Buffer.concat(chunks),type};}
async function saveImages(job,rows,notify,stopped=()=>false){const folder=path.join(job.folder,'images');fs.mkdirSync(folder,{recursive:true});let saved=0,failed=0;const manifest={};try{Object.assign(manifest,JSON.parse(fs.readFileSync(path.join(folder,'index.json'))));}catch{}
 for(const row of rows)for(const [i,url] of (row.images||[]).entries()){if(stopped())return {saved,failed,interrupted:true};const key=`${row.id}:${i}`;if(manifest[key]&&fs.existsSync(path.join(folder,manifest[key]))){saved++;continue;}try{const {bytes,type}=await imageBytes(url);const name=crypto.createHash('sha256').update(key).digest('hex').slice(0,24)+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif','image/avif':'avif'}[type]);fs.writeFileSync(path.join(folder,name),bytes);manifest[key]=name;saved++;fs.writeFileSync(path.join(folder,'index.json'),JSON.stringify(manifest,null,2));}catch{failed++;}notify({imagesSaved:saved,imagesFailed:failed});}
 return {saved,failed};}
function localImage(job,rowId,index){try{const folder=path.join(job.folder,'images');const manifest=JSON.parse(fs.readFileSync(path.join(folder,'index.json')));const name=manifest[`${rowId}:${index}`];if(!/^[a-f0-9]{24}\.(jpg|png|webp|gif|avif)$/.test(name||''))return null;const bytes=fs.readFileSync(path.join(folder,name));return {bytes,type:'image/'+(name.endsWith('.jpg')?'jpeg':name.split('.').pop())};}catch{return null;}}
module.exports={imageBytes,saveImages,localImage};
