const {Consent}=require('./consent.cjs');
const {app,BrowserWindow,Menu,ipcMain,dialog,shell}=require('electron');const fs=require('node:fs');const path=require('node:path');
const {Collector}=require('./collector.cjs');const {Repository,Queue,batch,readRows,queryRows,space}=require('./model.cjs');const {Sources}=require('./sources.cjs');const {imageBytes,localImage}=require('./assets.cjs');const {atomicJson}=require('./core.cjs');
app.setName('抖音评论采集助手');
const smoke=app.isPackaged&&process.argv.includes('--packaging-smoke-test');
const root=smoke?path.join(require('node:os').tmpdir(),'DouyinCommentCollector-smoke-'+process.pid):app.isPackaged?path.join(app.getPath('appData'),'DouyinCommentCollector'):path.resolve(__dirname,'..'),data=path.join(root,'data');fs.mkdirSync(data,{recursive:true});app.setPath('userData',path.join(data,'app'));
if(!app.requestSingleInstanceLock()){app.quit();}else{
let win,repo,collector,queue,sources,consent,closing=false;const imageCache=new Map();
function snapshot(){return {jobs:repo.jobs.map(j=>({...j,preview:[]})),settings:repo.settings,activeId:collector.active?.job.id,queueEnabled:queue.enabled,profile:sources.profile,version:app.getVersion()};}
function notify(){if(win&&!win.isDestroyed())win.webContents.send('state-update',snapshot());}
function handle(name,fn){ipcMain.handle(name,async(event,...args)=>{if(!win||event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame)throw new Error('请求来源不受支持。');try{consent.assertAllowed(name);return {ok:true,data:await fn(...args)};}catch(e){return {ok:false,error:e.message,code:e.code};}});}
app.on('second-instance',()=>{if(win){win.show();win.focus();}});
app.whenReady().then(()=>{
 Menu.setApplicationMenu(null);
 consent=new Consent(data);repo=new Repository(root,app.isPackaged?path.join(app.getPath('downloads'),'抖音评论采集助手'):undefined);collector=new Collector(data,job=>{repo.archive(job);repo.save();notify();});queue=new Queue(repo,collector,notify);sources=new Sources(collector,()=>{notify();queue.pump();});
 handle('consent-status',()=>consent.status());handle('consent-accept',value=>consent.accept(value));
 handle('state',()=>snapshot());handle('parse-batch',input=>batch(input));handle('preview',async input=>{try{return await sources.preview(input);}finally{queue.pump();}});
 handle('enqueue',(items,options)=>{if(!Array.isArray(items)||items.length>500)throw new Error('一次最多 500 条链接。');const result=repo.create(items,options);queue.start();notify();return result;});
 handle('queue-start',()=>queue.start());handle('queue-pause',()=>queue.pauseQueue());handle('remove-queued',id=>queue.remove(id));handle('retry',(id,part)=>queue.retry(id,part));
 handle('pause',()=>collector.pause());handle('resume',()=>collector.resume());handle('stop',()=>collector.stop());
 handle('login',()=>collector.login());handle('login-status',()=>collector.loginStatus());handle('logout',()=>collector.logout());
 handle('profile-start',(url,filter)=>sources.startProfile(url,filter));handle('profile-stop',()=>{sources.cancelled=true;});
 handle('choose-folder',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openDirectory','createDirectory'],defaultPath:repo.settings.output});if(!r.canceled){repo.settings.output=r.filePaths[0];repo.configure(repo.settings);}notify();return repo.settings.output;});
 handle('settings',value=>{const result=repo.configure(value);notify();return result;});handle('space',()=>({bytes:space(repo.settings.output),folder:repo.settings.output}));
 handle('comments',(id,filter={},page=1)=>{const job=repo.get(id);const rows=readRows(job.folder);const filtered=queryRows(rows,filter);const pageSize=50;page=Math.max(1,Math.min(Math.ceil(filtered.length/pageSize)||1,Number(page)||1));return {rows:filtered.slice((page-1)*pageSize,page*pageSize),total:filtered.length,rawTotal:rows.length,page,pageSize};});
 handle('replies',(id,rootId)=>readRows(repo.get(id).folder).filter(r=>r.rootId===rootId));
 handle('image',async(id,rowId,index)=>{const job=repo.get(id);const local=localImage(job,rowId,Number(index));if(local)return `data:${local.type};base64,${local.bytes.toString('base64')}`;let url;if(rowId==='cover')url=job.cover;else url=readRows(job.folder).find(r=>r.id===rowId)?.images?.[Number(index)];if(!url)throw new Error('没有图片地址。');if(imageCache.has(url))return imageCache.get(url);const result=await imageBytes(url);const encoded=`data:${result.type};base64,${result.bytes.toString('base64')}`;if(imageCache.size>=20)imageCache.delete(imageCache.keys().next().value);imageCache.set(url,encoded);return encoded;});
 handle('preview-image',async url=>{const img=await imageBytes(url);return `data:${img.type};base64,${img.bytes.toString('base64')}`;});
 handle('download-images',id=>{const job=repo.get(id);if(['queued','running','paused','needs_action'].includes(job.status))throw new Error('请等待任务结束后下载图片。');job.downloadImages=true;job.parts.images='pending';queue.retry(id,'images');});
 handle('open-result',async(id,type)=>{const j=repo.get(id);const names={video:'video.mp4',excel:'comments.xlsx',csv:'comments.csv',json:'comments.json',images:'images'};if(type!=='folder'&&!names[type])throw new Error('未知文件类型。');const file=type==='folder'?j.folder:path.join(j.folder,names[type]);if(!fs.existsSync(file))throw new Error('文件尚未生成或已被移动。');const error=await shell.openPath(file);if(error)throw new Error(error);});
 handle('export',async id=>{const job=repo.get(id);if(collector.active?.job.id===id)throw new Error('请等待当前任务完成后重新导出。');await collector.export({job,store:{rows:new Map(readRows(job.folder).map(r=>[r.id,r]))}});return '已重新生成全部原始结果的导出文件。';});
 handle('diagnostics',async()=>{const r=await dialog.showSaveDialog(win,{defaultPath:path.join(repo.settings.output,'抖音评论采集助手诊断.json'),filters:[{name:'JSON',extensions:['json']}]});if(r.canceled)return;const report={version:app.getVersion(),platform:process.platform,at:new Date().toISOString(),jobs:repo.jobs.map(j=>({id:j.id,status:j.status,parts:j.parts,comments:j.commentCount,stopReason:j.stopReason,issue:j.issue,checkpoint:j.checkpoint,errors:[j.failure,j.videoError,j.exportWarning].filter(Boolean).map(t=>String(t).replace(/https?:\/\/\S+/g,'[链接]').replace(/[A-Za-z]:[\\/][^\n]+/g,'[本地路径]'))}))};atomicJson(r.filePath,report);return '诊断文件已保存，不包含 Cookie、评论正文或昵称。';});
 handle('temp-list',()=>repo.jobs.flatMap(j=>['video.mp4.part'].map(name=>({path:path.join(j.folder,name),jobId:j.id}))).filter(f=>fs.existsSync(f.path)&&collector.active?.job.id!==f.jobId).map(f=>({...f,bytes:fs.statSync(f.path).size})));
 handle('temp-clean',async()=>{let files=repo.jobs.filter(j=>j.id!==collector.active?.job.id).map(j=>path.join(j.folder,'video.mp4.part')).filter(p=>fs.existsSync(p));if(!files.length)return '没有可清理的临时视频文件。';const answer=await dialog.showMessageBox(win,{type:'question',buttons:['取消','清理临时文件'],defaultId:0,cancelId:0,message:`清理 ${files.length} 个未完成的视频临时文件？`,detail:'仅删除任务目录中的 video.mp4.part，不删除已完成视频、评论或登录信息。'});if(answer.response!==1)return '已取消。';for(const f of files)fs.unlinkSync(f);return `已清理 ${files.length} 个临时文件。`;});
 win=new BrowserWindow({show:!smoke,width:1320,height:900,minWidth:1020,minHeight:720,title:'抖音评论采集助手',backgroundColor:'#f4f6f8',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 win.removeMenu();
 win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.loadFile(path.join(__dirname,'ui/index.html'));
 win.webContents.once('did-finish-load',()=>{atomicJson(path.join(data,'startup.json'),{ready:true,version:app.getVersion(),at:new Date().toISOString()});if(smoke){const report={ready:true,version:app.getVersion(),jobs:repo.jobs.length,consentAccepted:consent.status().accepted,browserProfileExists:fs.existsSync(path.join(data,'browser-profile')),menuRemoved:Menu.getApplicationMenu()===null,defaultOutput:repo.settings.output,dataRoot:root};fs.writeFileSync(path.join(require('node:os').tmpdir(),'DouyinCommentCollector-smoke-report.json'),JSON.stringify(report,null,2));win.close();return;}if(!app.isPackaged&&process.argv.includes('--verify-live')&&consent.status().accepted)require('../scripts/live-check.cjs')({repo,collector,sources}).catch(e=>atomicJson(path.join(data,'live-check-error.json'),{message:e.message}));});
 win.on('close',async event=>{if(closing)return;event.preventDefault();closing=true;queue.enabled=false;sources.cancelled=true;collector.stop();try{if(collector.active){win.webContents.send('closing');while(collector.active)await new Promise(r=>setTimeout(r,200));}await collector.close();repo.save();}finally{win.destroy();app.quit();}});
}).catch(e=>{dialog.showErrorBox('启动失败',e.message);app.quit();});
app.on('window-all-closed',()=>app.quit());
}
