const {parseInput,findVideo}=require('./core.cjs');
function profileURL(input){const match=String(input).match(/https:\/\/www\.douyin\.com\/user\/[A-Za-z0-9_.-]+/);if(!match)throw new Error('请粘贴作者主页长链接：https://www.douyin.com/user/…');return match[0];}
function post(d){const count=d.statistics?.comment_count;return {id:String(d.aweme_id),url:`https://www.douyin.com/video/${d.aweme_id}`,title:d.desc||'未命名作品',author:d.author?.nickname||'',pageCommentCount:count!==null&&count!==undefined&&count!==''&&Number.isFinite(Number(count))&&Number(count)>=0?Number(count):null,authorUrl:d.author?.sec_uid?`https://www.douyin.com/user/${d.author.sec_uid}`:'',cover:d.video?.cover?.url_list?.[0]||d.images?.[0]?.url_list?.[0]||'',createdAt:d.create_time?new Date(d.create_time*1000).toISOString():'',type:d.images?.length?'image':'video'};}
function selectPosts(items,filter={}){const from=filter.from?Date.parse(filter.from+'T00:00:00+08:00'):-Infinity,to=filter.to?Date.parse(filter.to+'T23:59:59.999+08:00'):Infinity;if(Number.isNaN(from)||Number.isNaN(to)||from>to)throw new Error('主页日期范围不正确。');return items.filter(p=>(!filter.from&&!filter.to)||(p.createdAt&&Date.parse(p.createdAt)>=from&&Date.parse(p.createdAt)<=to)).slice(0,Number(filter.limit)||100);}
class Sources{
 constructor(collector,notify){this.c=collector;this.notify=notify;this.profile={status:'idle',items:[]};}
 async preview(input){if(this.c.active||this.c.browsing)throw new Error('请等待当前浏览器操作结束；可以先识别链接并直接入队。');this.c.browsing=true;let page,listener;try{const ctx=await this.c.browser();page=ctx.pages()[0]||await ctx.newPage();let parsed=parseInput(input);let detail=null;
 listener=async res=>{if(res.url().includes('/aweme/detail/'))try{const d=await res.json();detail=findVideo(d,parsed.id)||detail;}catch{}};page.on('response',listener);await page.goto(parsed.url,{waitUntil:'domcontentloaded',timeout:30000});if(!parsed.id)parsed=parseInput(page.url());
 for(let i=0;i<12&&!detail;i++){const embedded=await page.evaluate(()=>window._ROUTER_DATA||null).catch(()=>null);detail=findVideo(embedded,parsed.id)||detail;if(!detail)await new Promise(r=>setTimeout(r,700));}
 if(!detail)throw new Error('未取得作品预览。请检查 Edge 中登录或验证提示后重试。');return post(detail);
 }finally{if(page&&listener)page.off('response',listener);this.c.browsing=false;}}
 startProfile(input,filter){if(this.c.active||this.c.browsing)throw new Error('请先暂停队列并结束当前采集，再读取主页。');const url=profileURL(input);if(!Number.isInteger(Number(filter.limit))||Number(filter.limit)<1||Number(filter.limit)>500)throw new Error('主页作品数量为 1～500。');selectPosts([],filter);this.c.browsing=true;this.cancelled=false;this.profile={status:'running',items:[],scanned:0,message:'正在读取主页作品…'};this.notify();this.runProfile(url,filter).catch(e=>{this.profile.status='partial';this.profile.message=e.message;}).finally(()=>{this.c.browsing=false;this.notify();});return this.profile;}
 async runProfile(url,filter){const ctx=await this.c.browser();const page=ctx.pages()[0]||await ctx.newPage();const uid=new URL(url).pathname.split('/').pop();const all=new Map();let end=false,last=Date.now();const pending=new Set();
 const listener=res=>{let u;try{u=new URL(res.url());}catch{return;}if(!u.hostname.endsWith('.douyin.com')||!u.pathname.includes('/aweme/post/')||u.searchParams.get('sec_user_id')!==uid)return;const p=(async()=>{const d=await res.json();if(!Array.isArray(d.aweme_list))return;for(const item of d.aweme_list)all.set(String(item.aweme_id),post(item));if(d.has_more===0)end=true;last=Date.now();this.profile.items=selectPosts([...all.values()],filter);this.profile.scanned=all.size;this.notify();})().catch(()=>{});pending.add(p);p.finally(()=>pending.delete(p));};
 page.on('response',listener);try{await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});for(let round=0;!this.cancelled&&!end&&this.profile.items.length<Number(filter.limit);round++){if(page.isClosed())throw new Error('浏览器窗口已关闭。');if(Date.now()-last>45000)break;await page.mouse.wheel(0,950);await new Promise(r=>setTimeout(r,2000));if(round>150)break;}}
 finally{page.off('response',listener);await Promise.allSettled([...pending]);}
 this.profile.status=this.cancelled?'partial':end||this.profile.items.length>=Number(filter.limit)?'completed':'partial';this.profile.message=`已读取 ${all.size} 个作品，筛选后 ${this.profile.items.length} 个。`+(this.profile.status==='partial'?' 列表可能不完整；可检查浏览器后重新读取。':'');
 }
}
module.exports={Sources,profileURL,selectPosts,post};
