const $=id=>document.getElementById(id);let state={jobs:[],profile:{items:[]}},drafts=[],selected=new Set(),currentId=null,page=1,pageCount=1,source='links',lastProfile='',loadingComments=0;
const names={queued:'排队中',running:'采集中',paused:'已暂停',needs_action:'需要操作',completed:'已完成',partial:'部分完成',failed:'失败',cancelled:'已结束',interrupted:'上次中断',pending:'等待',skipped:'未选择'};
const titles={collect:['开始采集','从作品链接或作者主页建立采集任务。'],tasks:['任务中心','逐个处理任务，随时暂停、续采与分项重试。'],library:['作品与评论','浏览全部已采集评论，筛选不会改变原始结果。'],settings:['设置','管理登录、保存位置和运行方式。']};
function notice(t){$('notice').hidden=!t;$('notice').textContent=t||'';}
async function call(name,...args){let r=await window.assistant.call(name,...args);if(!r.ok&&r.code==='CONSENT_REQUIRED'){if(!await showConsent())throw new Error('已取消，未执行采集操作。');r=await window.assistant.call(name,...args);}if(!r.ok){notice(r.error);throw new Error(r.error);}return r.data;}
let consentPending=null;
async function showConsent(){if(consentPending)return consentPending;let finish;consentPending=new Promise(resolve=>{finish=resolve;});const pending=consentPending;const dialog=$('consent-dialog'),body=$('consent-body'),check=$('consent-check'),agree=$('consent-agree');const close=value=>{dialog.close();consentPending=null;finish(value);};try{const r=await window.assistant.call('consent-status');if(!r.ok)throw new Error(r.error);const statement=r.data;body.textContent=statement.text;check.checked=false;check.disabled=true;agree.disabled=true;$('consent-error').textContent='';$('consent-progress').textContent='请阅读完整声明，滚动到底部后勾选同意。';$('consent-cancel').textContent=statement.accepted?'关闭':'不同意，取消采集';let reached=false;const scroll=()=>{if(body.scrollTop+body.clientHeight>=body.scrollHeight-4){reached=true;check.disabled=false;$('consent-progress').textContent='已到达声明末尾，请自行确认理解后勾选。';}};body.onscroll=scroll;check.onchange=()=>{agree.disabled=!reached||!check.checked;};$('consent-cancel').onclick=()=>close(false);dialog.oncancel=e=>{e.preventDefault();close(false);};agree.onclick=async()=>{if(!reached||!check.checked)return;agree.disabled=true;try{const result=await window.assistant.call('consent-accept',{version:statement.version,hash:statement.hash,agreed:true});if(!result.ok)throw new Error(result.error);close(true);}catch(e){$('consent-error').textContent=e.message;agree.disabled=false;}};dialog.showModal();body.scrollTop=0;scroll();}catch(e){notice(e.message);close(false);}return pending;}
function el(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function action(text,fn){const b=el('button',text);b.onclick=()=>Promise.resolve().then(fn).catch(e=>notice(e.message));return b;}
function on(id,fn){$(id).onclick=async()=>{try{await fn();}catch(e){notice(e.message);}};}
function view(name){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!=='view-'+name);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('page-title').textContent=titles[name][0];$('page-subtitle').textContent=titles[name][1];if(name==='library'&&currentId)loadComments();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function time(t){return t?new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'时间未知';}
const defaultLimit=()=>Number($('limit').value||100);
const countKnown=d=>d.pageCommentCount!==null&&d.pageCommentCount!==undefined&&Number.isFinite(Number(d.pageCommentCount));
function prepareDraft(d){return {...d,limit:d.limit??defaultLimit()};}
async function previewDraft(d){const result=await call('preview',d.url);const i=drafts.indexOf(d);if(i>=0){drafts[i]={...d,...result};renderDrafts();}}
function renderDrafts(){const box=$('drafts');box.replaceChildren();drafts.forEach((d,i)=>{d.limit??=defaultLimit();const row=el('div',undefined,'draft');const check=el('input');check.type='checkbox';check.checked=selected.has(i);check.onchange=()=>{check.checked?selected.add(i):selected.delete(i);selection();};const info=el('div');info.append(el('b',d.title||d.id||d.url),el('small',`${d.author||'待预览'}${d.createdAt?' · '+time(d.createdAt):''}${d.type==='image'?' · 图文':''}`),el('small',`平台评论总数：${countKnown(d)?Number(d.pageCommentCount).toLocaleString('zh-CN')+' 条':'待获取'}`));const label=el('label','采集上限 ', 'draft-limit');const input=el('input');input.type='number';input.min=1;input.max=20000;input.value=d.limit;input.oninput=()=>{d.limit=Number(input.value);d.limitCustomized=true;};label.append(input,el('span',' 条'));row.append(check,info,label);if(d.cover)row.append(action('封面',()=>showImage(()=>call('preview-image',d.cover))));row.append(action('读取资料 / 预览',()=>previewDraft(d)));box.append(row);});selection();}
function selection(){$('selected-count').textContent=`已选 ${selected.size} / ${drafts.length} 个作品`;const items=[...selected].map(i=>drafts[i]);const known=items.filter(countKnown);const unknown=items.length-known.length;$('platform-total').textContent=!items.length?'平台评论总数：未选择作品':!known.length?'平台评论总数：待获取':`${items.length>1?'已选作品':''}平台评论总数：${known.reduce((n,d)=>n+Number(d.pageCommentCount),0).toLocaleString('zh-CN')} 条${unknown?'（另有 '+unknown+' 个待获取）':''}`;}
$('limit').onchange=()=>{for(const d of drafts)if(!d.limitCustomized)d.limit=defaultLimit();renderDrafts();};
on('apply-limit',()=>{for(const d of drafts){d.limit=defaultLimit();d.limitCustomized=false;}renderDrafts();});
on('read-counts',async()=>{const items=[...selected].map(i=>drafts[i]);$('read-counts').disabled=true;try{for(const d of items){if(!drafts.includes(d))break;await previewDraft(d);}}finally{$('read-counts').disabled=false;}});
function switchSource(mode){source=mode;$('links-panel').hidden=mode!=='links';$('profile-panel').hidden=mode!=='profile';$('source-links').classList.toggle('selected',mode==='links');$('source-profile').classList.toggle('selected',mode==='profile');drafts=mode==='profile'?(state.profile.items||[]).map(prepareDraft):[];selected.clear();renderDrafts();}
on('source-links',()=>switchSource('links'));on('source-profile',()=>switchSource('profile'));
on('parse',async()=>{const r=await call('parse-batch',$('input').value);drafts=r.items.map(prepareDraft);selected=new Set(drafts.map((_,i)=>i));renderDrafts();$('parse-summary').textContent=`识别 ${r.items.length} 条，重复 ${r.duplicates} 条，无效 ${r.errors.length} 条`;notice(r.errors.map(e=>e.input+'：'+e.error).join('\n'));if(drafts.length===1&&!state.activeId&&state.profile.status!=='running')await previewDraft(drafts[0]);});
on('select-all',()=>{selected=new Set(drafts.map((_,i)=>i));renderDrafts();});on('select-none',()=>{selected.clear();renderDrafts();});
on('enqueue',async()=>{if(!selected.size)throw new Error('请先识别链接或读取主页，勾选要采集的作品。');const items=[...selected].map(i=>drafts[i]);if($('video').checked&&items.some(d=>d.type==='image'))throw new Error('所选作品包含图文，请取消“下载视频”或取消勾选图文作品。');const r=await call('enqueue',items,{limit:Number($('limit').value),video:$('video').checked,comments:$('comments').checked,replies:$('replies').checked,downloadImages:$('images').checked});notice(`已加入 ${r.created.length} 个任务，跳过 ${r.skipped.length} 个已排队作品。`);view('tasks');});
on('profile-read',async()=>{await call('profile-start',$('profile-url').value,{from:$('profile-from').value,to:$('profile-to').value,limit:Number($('profile-limit').value)});});on('profile-stop',()=>call('profile-stop'));
on('queue-start',()=>call('queue-start'));on('queue-pause',()=>call('queue-pause'));
function partsText(j){return ['video','comments','images'].map((k,i)=>`${['视频','评论','图片'][i]}：${names[j.parts?.[k]||'pending']}`).join('　');}
function renderTasks(){const box=$('tasks');box.replaceChildren();$('queue-state').textContent=state.queueEnabled?'队列运行中':'后续任务已暂停';if(!state.jobs.length)box.append(el('p','还没有任务，先添加作品链接。','empty'));[...state.jobs].reverse().forEach(j=>{const row=el('div',undefined,'task');const info=el('div');info.append(el('b',j.title||j.videoId||'短链作品'),el('small',`${names[j.status]} · ${j.commentCount||0}/${j.limit} 条 · ${partsText(j)}`),el('p',j.message||'等待执行'));if(j.videoBytes)info.append(el('small',`视频 ${(j.videoBytes/1048576).toFixed(1)} MB${j.videoTotal?' / '+(j.videoTotal/1048576).toFixed(1)+' MB':''}`));const buttons=el('div',undefined,'task-buttons');buttons.append(action('查看',()=>{currentId=j.id;view('library');renderDetail();}));if(j.id===state.activeId){if(j.status==='running')buttons.append(action('暂停',()=>call('pause')));if(['paused','needs_action'].includes(j.status))buttons.append(action('继续',()=>call('resume')));buttons.append(action('结束并保存',()=>call('stop')));}else if(j.status==='queued')buttons.append(action('移出队列',()=>call('remove-queued',j.id)));else{buttons.append(action('继续原任务',()=>call('retry',j.id,'all')));if(j.video)buttons.append(action('重试视频',()=>call('retry',j.id,'video')));if(j.comments&&j.parts?.comments!=='completed')buttons.append(action('续采评论',()=>call('retry',j.id,'comments')));if(j.downloadImages)buttons.append(action('重试图片',()=>call('retry',j.id,'images')));}row.append(info,buttons);box.append(row);});}
function renderDetail(){const j=state.jobs.find(j=>j.id===currentId);$('detail').hidden=!j;if(!j)return;$('job-select').value=j.id;$('detail-title').textContent=j.title||j.videoId;$('detail-message').textContent=j.message||'';$('detail-parts').textContent=partsText(j);$('logs').textContent=`停止原因：${j.stopReason||'尚未结束'}\n`+(j.messages||[]).map(m=>m.time+' '+m.text).join('\n');}
function renderState(s){state=s;renderTasks();const select=$('job-select');select.replaceChildren();s.jobs.forEach(j=>{const o=el('option',j.title||j.videoId||j.id);o.value=j.id;select.append(o);});if(!currentId&&s.jobs.length)currentId=s.jobs[0].id;renderDetail();$('output').textContent=s.settings.output;$('settings-output').textContent=s.settings.output;$('version').textContent='本地版 · '+s.version;
 $('profile-message').textContent=s.profile.message||'';$('profile-read').disabled=s.profile.status==='running';const profileKey=JSON.stringify(s.profile.items);if(source==='profile'&&profileKey!==lastProfile){const oldIds=new Set([...selected].map(i=>drafts[i]?.id));const previous=new Map(drafts.map(d=>[d.id,d]));drafts=s.profile.items.map(d=>prepareDraft({...d,limit:previous.get(d.id)?.limit,limitCustomized:previous.get(d.id)?.limitCustomized}));selected=new Set(drafts.map((d,i)=>oldIds.has(d.id)?i:-1).filter(i=>i>=0));renderDrafts();}lastProfile=profileKey;
}
function filters(){return {keyword:$('f-keyword').value,from:$('f-from').value,to:$('f-to').value,minLikes:$('f-min').value,maxLikes:$('f-max').value,region:$('f-region').value,level:$('f-level').value,sort:$('f-sort').value};}
async function showImage(loader){$('large-image').removeAttribute('src');$('image-error').textContent='正在加载图片…';$('image-dialog').showModal();try{$('large-image').src=await loader();$('image-error').textContent='';}catch(e){$('image-error').textContent=e.message;}}
on('close-image',()=>$('image-dialog').close());
function commentRow(r){const tr=el('tr');const author=el('td',r.nickname);author.append(el('small',`${r.level===1?'主评论':'回复'} · ${r.region||'属地未知'}\n${time(r.createdAt)}`));const text=el('td',r.text);if(r.images?.length){const block=el('div',undefined,'row');block.append(el('small',`[图片评论 · ${r.images.length} 张]`));r.images.forEach((_,i)=>block.append(action(`预览 ${i+1}`,()=>showImage(()=>call('image',currentId,r.id,i)))));text.append(block);}if(r.level===1&&r.replyCount){const target=currentId;let expanded=false;const container=el('div',undefined,'reply-block');text.append(action(`查看已采集回复（平台显示 ${r.replyCount}）`,async()=>{if(expanded){container.replaceChildren();expanded=false;return;}const replies=await call('replies',target,r.id);container.replaceChildren();if(!replies.length)container.append(el('p','尚未采集到这条主评论的回复。'));for(const reply of replies){const child=el('div',`${reply.nickname}：${reply.text}`);if(reply.images?.length)reply.images.forEach((_,i)=>child.append(action('图片预览',()=>showImage(()=>call('image',target,reply.id,i)))));container.append(child);}expanded=true;}),container);}tr.append(author,text,el('td',String(r.likes)));return tr;}
async function loadComments(){if(!currentId)return;const seq=++loadingComments;const result=await call('comments',currentId,filters(),page);if(seq!==loadingComments)return;page=result.page;pageCount=Math.ceil(result.total/50)||1;$('comment-rows').replaceChildren(...result.rows.map(commentRow));$('comment-total').textContent=`符合条件 ${result.total} 条 / 原始 ${result.rawTotal} 条`;$('page-number').textContent=`${page} / ${pageCount}`;$('prev').disabled=page<=1;$('next').disabled=page>=pageCount;}
on('filter',()=>{page=1;return loadComments();});on('refresh-comments',()=>loadComments());on('prev',()=>{page--;return loadComments();});on('next',()=>{page++;return loadComments();});on('reset-filter',()=>{['f-keyword','f-from','f-to','f-max','f-region','f-level','f-sort'].forEach(id=>$(id).value='');$('f-min').value=0;page=1;return loadComments();});$('job-select').onchange=()=>{currentId=$('job-select').value;page=1;renderDetail();loadComments().catch(e=>notice(e.message));};
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>currentId&&call('open-result',currentId,b.dataset.open).catch(()=>{}));on('export',async()=>notice(await call('export',currentId)));on('download-images',async()=>{await call('download-images',currentId);notice('图片下载任务已入队。');});
on('login',async()=>{notice('请在独立 Edge 窗口完成登录或验证。');await call('login');});on('check-login',async()=>{$('login-state').textContent=(await call('login-status')).message;});on('logout',async()=>{if(confirm('退出专用浏览器中的抖音登录？下次采集需要重新登录，已下载文件不会删除。'))$('login-state').textContent=await call('logout');});
on('folder',()=>call('choose-folder'));on('check-space',async()=>{$('disk').textContent=`剩余 ${((await call('space')).bytes/1073741824).toFixed(1)} GB`;});on('save-settings',async()=>{await call('settings',{interval:Number($('interval').value),retries:Number($('retries').value)});notice('设置已保存，下一个任务生效。');});on('diagnostics',async()=>notice(await call('diagnostics')));on('temp-clean',async()=>notice(await call('temp-clean')));
on('view-consent',()=>showConsent());
window.assistant.onUpdate(renderState);window.assistant.onClosing(()=>notice('正在保存进度并关闭，请稍候…'));call('state').then(s=>{renderState(s);$('interval').value=s.settings.interval;$('retries').value=s.settings.retries;}).catch(()=>{});
